version: "3.8"
services:
  app:
    build: ./docker
    volumes: ./backend:/var/www/html
    ports: ["9000:9000"]
    depends_on: ["db","redis"]
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: pos
      POSTGRES_USER: pos
      POSTGRES_PASSWORD: pos
    volumes: db-data:/var/lib/postgresql/data
  redis:
    image: redis:7
volumes:
  db-data:
